name: test

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
      - name: Test with pytest
        run: python -m pytest -v