name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HerokuDeploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pes-econnect" #Must be unique in Heroku
          heroku_email: "pol.burkardt@estudiantat.upc.edu"
      - name: Test with pytest
          run: |
          python -m pytest -v
